### ISSUE TITLE
Use a secret ref or mount instead of env var for auth data

### ISSUE THREAD

**Issue by valorl** [titansoft-pte-ltd/imagepullsecret-patcher#7]
It's generally considered less secure to use env vars for sensitive data. Have there been any discussions around this? 

I think this could be improved by:

Instead of including the auth data in an env var, use an env var to hold a reference to a secret which holds the auth data. This secret could be deployed together with the patcher in the same namespace and the patcher could then read it and copy the auth data from it into each new image-pull-secret.

**Comment by billjh** [comment]
Hi @valorl thanks for your suggestion!

It's indeed better with secret ref rather than plain text for the auth secret. If I understand correctly, we are doing exactly this way in the deployment example:

https://github.com/titansoft-pte-ltd/imagepullsecret-patcher/blob/dc1643fb625897d31076e755c4e8499d449aaa22/deploy-example/kubernetes-manifest/2_deployment.yaml#L1-L8

https://github.com/titansoft-pte-ltd/imagepullsecret-patcher/blob/dc1643fb625897d31076e755c4e8499d449aaa22/deploy-example/kubernetes-manifest/2_deployment.yaml#L38-L42

**Comment by valorl** [comment]
Hi @billjh, thanks for the reply and sorry for the delay, I've been busy.

The `secretKeyRef` in that example is still used to populate an env var `CONFIG_DOCKERCONFIGJSON`. 
The concern I'm referring to relates to the general security issues with using env vars for secrets in containers due to the fact that you may be able to read container env vars in the host filesystem via `/proc/` . Yes, it does require root, so it's not a major issue, but in some environments people might care about that. 

The alternative approach I'm suggesting is to skip the env var and let the patcher fetch the secret directly (e.g. on initialization) from the K8S API. That way the secret only exists in etcd and in patcher memory.

I'm no container security expert, I've just seen comments about this around the community so I wanted to hear your thoughts on this :)

**Comment by billjh** [comment]
Hi @valorl, thanks for your explanation! I am more aware of the security concern you raised.
Container security is new to me also, so I will leave the issue open and do some research on it. 

Meanwhile, PRs are always welcomed to anyone here. Cheers!

**Comment by billjh** [comment]
This issue should be resolved with #14 thanks to @ryanmt 👏
